### ISSUE TITLE
All requests are answered with http code 502: Bad Gateway

### ISSUE THREAD

**Issue by Gaspode69** [alphaess-developer/alphacloud_open_api#85]
Since a few hours, all requests are answered with http code 502.

**Comment by MonsterEnergy-wtf** [comment]
Yes, I also face this. I gues the nginx is misconfigured somehow.
Not sure if really from Alpha ESS is looking here for this...

**Comment by neiloakley** [comment]
“18/09/2024, 16:23:22[node: Alpha ESS](http://192.168.7.7:1880/#)
msg : string[105]
"There was an error communicating with Alpha Services: AxiosError: Request failed with status code 502 (0)"

**Comment by beastien** [comment]
I have the same problem. Error from my logs.

This error originated from a custom integration.

Logger: alphaess.alphaess
Source: custom_components/alphaess/__init__.py:48
integration: Alpha ESS (documentation, issues)
First occurred: September 18, 2024 at 10:51:21 PM (4 occurrences)
Last logged: 5:31:02 AM

502, message='Bad Gateway', url='https://openapi.alphaess.com/api/getEssList'
Error: 502, message='Bad Gateway', url='https://openapi.alphaess.com/api/getEssList' when calling https://openapi.alphaess.com/api/getEssList

**Comment by tbgoose** [comment]
Me too, looks like api is down...
```
This error originated from a custom integration.

Logger: alphaess.alphaess
Source: custom_components/alphaess/__init__.py:48
integration: Alpha ESS (documentation, issues)
First occurred: September 18, 2024 at 8:59:24 PM (6 occurrences)
Last logged: 8:45:40 AM

502, message='Bad Gateway', url='https://openapi.alphaess.com/api/getEssList'
Error: 502, message='Bad Gateway', url='https://openapi.alphaess.com/api/getEssList' when calling https://openapi.alphaess.com/api/getEssList
```
```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: September 18, 2024 at 8:59:24 PM (3 occurrences)
Last logged: 8:45:40 AM

Error setting up entry alpha1795b2a096f813b0 for alphaess
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/__init__.py", line 49, in async_setup_entry
    for unit in ESSList:
TypeError: 'NoneType' object is not iterable
```
```
This error originated from a custom integration.

Logger: alphaess.alphaess
Source: custom_components/alphaess/coordinator.py:62
integration: Alpha ESS (documentation, issues)
First occurred: September 18, 2024 at 12:00:46 AM (10 occurrences)
Last logged: September 18, 2024 at 8:58:22 PM

Unexpected json_response : {'code': 6026, 'msg': 'network is busy', 'expMsg': None, 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getOneDateEnergyBySn?sysSn=AL20021190XXXXXX&queryDate=2024-09-18
Unexpected json_response : {'code': 6026, 'msg': 'network is busy', 'expMsg': 'nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.\n### The error may exist in class path resource [mapper/td/SysColdataMapper.xml]\n### The error may involve com.alphaess.api.mapper.td.SysColdataMapper.selectOneDayLastPowerBysn\n### The error occurred while executing a query\n### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.', 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getOneDateEnergyBySn?sysSn=AL20021190XXXXXX&queryDate=2024-09-18
502, message='Bad Gateway', url='https://openapi.alphaess.com/api/getEssList'
Error: 502, message='Bad Gateway', url='https://openapi.alphaess.com/api/getEssList' when calling https://openapi.alphaess.com/api/getEssList
'NoneType' object is not iterable
```

**Comment by Poshy163** [comment]
Just an update for yall, not much we can do other than complain it seems 

![image](https://github.com/user-attachments/assets/80f657e3-278b-47ab-9ff7-a59f4706a4e1)

**Comment by Gaspode69** [comment]
Works again.
